name: pueri_project
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_messaging: ^14.7.19

  pinput: ^4.0.0
  fluttertoast: ^8.2.4
  expandable_text: 2.3.0
  flutter_credit_card: ^4.0.1
  font_awesome_flutter: ^10.6.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  intl: ^0.18.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  buildcondition: ^0.0.4
  permission_handler: ^11.1.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  connectivity: ^3.0.6
  file_picker: ^6.1.1
  sms_otp_auto_verify: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
